src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>B2B</fullName>
        <active>true</active>
        <label>B2B</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Actual_Launch_Date__c</fullName>
        <label>Actual Launch Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Client_Slug__c</fullName>
        <label>Client Slug</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Provisioning</fullName>
        <active>true</active>
        <businessProcess>Coursera For Business</businessProcess>
        <label>Provisioning</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>B2B</fullName>
        <active>true</active>
        <description>B2B Contact Type</description>
        <label>B2B</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Customer_Pulse__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Coursera_Org_ID</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enterprise_Contract_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Customer Contract ID recorded in Coursera Prod env</description>
        <externalId>true</externalId>
        <inlineHelpText>Customer Contract ID recorded in Coursera Prod env</inlineHelpText>
        <label>Enterprise Contract ID</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Enterprise_Customer_Slug__c</fullName>
        <description>Customer slug recorded in Coursera Prod env</description>
        <inlineHelpText>Customer slug recorded in Coursera Prod env</inlineHelpText>
        <label>Enterprise Customer Slug</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <label>Customer Pulse</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Customer Pulse Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Pulse</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>B2B</fullName>
        <active>true</active>
        <businessProcess>B2B</businessProcess>
        <description>Lead process for B2B leads</description>
        <label>B2B</label>
    </recordTypes>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Actual_Launch_Date__c</fullName>
        <label>Actual Launch Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TriggerHandlerClass_Test.cls
@isTest(SeeAllData= true)
private class TriggerHandlerClass_Test {
	static Profile p;
	static UserRole ur;
	static User standardUser;
	static Account a;
	static Contact contact;
	static Opportunity o;
	static Case c;
	static Customer_Management__c cm;
	static Task task;

	@isTest static void test_UpdateAccountOnCustomerPulse() {
		data();
		Test.startTest();
		Customer_Pulse__c cp = new Customer_Pulse__c(Enterprise_Contract_ID__c = '12324', Enterprise_Customer_Slug__c = 'xyz');
		insert cp;	
		Test.stopTest();	
	}
	
	@isTest static void test_InsertOrUpdate_IndustryGroupOnLead() {
		IndustryBuckets__c ib = new IndustryBuckets__c(Name = 'TestName', Industry__c = 'Household Durables', Industry_Group__c ='Consumer Durables & Apparel');
		insert ib;
		List<Lead> leadsToInsert = new List<Lead>();		
		Lead l1 = new Lead(LastName = 'TestLastName1', Company = 'Test Company1', Status = 'Working');
		leadsToInsert.add(l1);
		Lead l2 = new Lead(LastName = 'TestLastName2', Company = 'Test Company2', Status = 'Working', Industry='xyz');
		leadsToInsert.add(l2);
		Lead l3 = new Lead(LastName = 'TestLastName3', Company = 'Test Company3', Status = 'Working', Industry='Household Durables', Industry_Group_Clearbit__c = 'Consumer Durables & Apparel');
		leadsToInsert.add(l3);
		insert leadsToInsert;
		l1.Industry='Household Durables';
		update l1;		
	}

	@isTest static void test_CreateNewQBRsForCompletedQBRs() {
		data();
		task = new Task(whoId = contact.id, whatId = cm.id, ActivityDate = system.today(), Status = 'Open', Priority = 'Normal', Type = 'QBR',subject = 'Q3-2017 QBR');
        insert task; 
		Test.startTest();
		task.Status = 'Completed';
		update task;
		Test.stopTest();		
	}

	@isTest static void test_CreateNewQBRsForClosedWonNewBusinessOpportunities() {
		data();
		Id caseRecordTypeId = Schema.Sobjecttype.Case.getRecordTypeInfosByName().get('Provisioning').getRecordTypeId();         
		Case c = new Case(AccountId = a.id, Opportunity__c = o.id, RecordTypeId = caseRecordTypeId, Actual_Launch_Date__c = system.today(), Implementation_Status__c = 'On Track');
		insert c; 		
		Test.startTest();
		c.Implementation_Status__c = 'Launched';
		update c;
		Test.stopTest();		
	}

	static void data(){
		p = [SELECT p.Name,p.Id from Profile p where p.Name='Standard User' limit 1]; 
		
		ur = [Select id from UserRole where Name = 'Customer Success-APAC' limit 1];  

		standardUser = [Select id from User limit 1];             
        
        /*standardUser = new User(UserName='testMexyz@google.com',LastName='Test',email='test@google.com',alias='testMeXy',communitynickname='testMex',
        TimeZoneSidKey='America/New_York',LocaleSidKey='en_US',EmailEncodingKey='ISO-8859-1',ProfileId=p.Id,LanguageLocaleKey='en_US',UserRoleId=ur.Id);
        insert standardUser;*/

        a = new Account(Name = 'TestAccount', Type = 'B2B: Corporate', Account_Manager__c = standardUser.id);
		insert a;
		
		contact = new Contact(AccountID = a.id, LastName = 'xyz');
		insert contact;
		
		o = new Opportunity(Name = 'TestOppty', AccountId = a.id, CloseDate = System.Today()+7, StageName = 'Proposal', Type = 'New business');
		insert o;
		
		c = new Case (Status = 'New', Origin = 'Email', Client_Slug__c = 'xyz', Opportunity__c = o.id);
		insert c;
    	
    	cm = new Customer_Management__c (Account__c = a.id);
    	insert cm;   	    	
    	
	}
	
}